version: "3"

services:
  app:
    build: .
    ports:
      - "3050:3050"
    volumes:
      - ./:/usr/src/
      - ~/.cache/puppeteer:/root/.cache/puppeteer 
    restart: always
    entrypoint: "./entrypoint.sh"
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
