version: "3"

services:
  app:
    build: .
    ports:
      - "3050:3050"
    volumes:
      - ./:/usr/src/
      - ~/.cache/puppeteer:/root/.cache/puppeteer 
    restart: always
    entrypoint: "./entrypoint.sh"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: