version: "3"

services:
  app:
    build: .
    ports:
      - "3050:3050"
    volumes:
      - ./:/usr/src/
      - ~/.cache/puppeteer:/root/.cache/puppeteer 
    restart: always
    entrypoint: "./entrypoint.sh"